MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("coco_rsna_train_2018",)
  TEST: ("coco_rsna_val_2018",)
SOLVER:
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (48000, 64000)
  MAX_ITER: 72000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 200
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: ./outputs/
